---
- name: "Configure {{ item }}"
  template:
    src: wgX.conf.j2
    dest: "/etc/wireguard/{{ item }}.conf"
    mode: '0400'
  register: configuration

- name: "Manage wg-quick@{{ item }} service"
  service:
    name: "wg-quick@{{ item }}"
    state: "{{ 'started' if wireguard_interfaces[item]['service'] == 'yes' else 'stopped' }}"
    enabled: "{{ wireguard_interfaces[item]['service'] }}"
  tags: install
  when: (wireguard_manage_services and wireguard_interfaces[item]['service'] is defined)

- name: "Sync config of wireguard interface {{ item }}"
  shell: "wg syncconf {{ item }} <(wg-quick strip {{ item }})"
  args:
    executable: /bin/bash
  when: >
    (configuration is changed and
      wireguard_manage_services and
      wireguard_interfaces[item]['service'] is defined and
      wireguard_interfaces[item]['service'] == 'yes')

- name: "Sync routes of wireguard interface {{ item }}"
  shell: "/usr/local/bin/wg-routes {{ item }}"
  args:
    executable: /bin/bash
  when: >
    (configuration is changed and
      wireguard_manage_services and
      wireguard_interfaces[item]['service'] is defined and
      wireguard_interfaces[item]['service'] == 'yes')

