---
- include_tasks: "{{ ansible_distribution | lower }}_repositories.yml"
- include_tasks: "{{ ansible_distribution | lower }}_linux_headers.yml"

- name: Install wireguard
  apt:
    name: "{{ 'wireguard=' + wireguard_version if wireguard_version != '' else 'wireguard' }}"
    state: present
    update_cache: yes
  register: upgrade

