---
- include_tasks: "{{ ansible_distribution | lower }}_repositories.yml"
  tags:
    - wireguard_install
- include_tasks: "{{ ansible_distribution | lower }}_linux_headers.yml"
  tags:
    - wireguard_install

- name: Install wireguard
  apt:
    name: "{{ 'wireguard=' + wireguard_version if wireguard_version != '' else 'wireguard' }}"
    state: present
    update_cache: yes
  register: upgrade
  tags:
    - wireguard_install
    - wireguard_upgrade

