---
- include_tasks: "{{ ansible_os_family | lower }}_packages.yml"
  tags:
    - wireguard_install
    - wireguard_upgrade

- name: Create /etc/wireguard
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
  tags:
    - wireguard_install
    - wireguard_upgrade

- name: 'Create wireguard systemd file'
  template:
    src: wg-quick.service.j2
    dest: '/lib/systemd/system/wg-quick@.service'
    mode: '0644'
  register: systemd_wg
  tags:
    - wireguard_install
    - wireguard_upgrade

- name: 'Systemd daemon reload'
  command: 'systemctl daemon-reload'
  when: systemd_wg is changed
  tags:
    - wireguard_install
    - wireguard_upgrade

- include_tasks: configure_keys.yml
  loop: "{{ wireguard_interfaces.keys() | list }}"
  tags:
    - wireguard_configure
  when: wireguard_manage_keys

- include_tasks: configure_network.yml
  loop: "{{ wireguard_interfaces.keys() | list }}"
  tags:
    - wireguard_configure

- include_tasks: restart.yml
  loop: "{{ wireguard_interfaces.keys() | list }}"
  tags:
    - wireguard_upgrade

