---
- name: "Upgrade restart wg-quick@{{ item }} service"
  service:
    name: "wg-quick@{{ item }}"
    state: "{{ 'restarted' if wireguard_interfaces[item]['service'] == 'yes' else 'stopped' }}"
  when: >
    (upgrade is changed and
      wireguard_manage_services and
      wireguard_interfaces[item]['service'] is defined and
      wireguard_upgrade_restart)
  tags:
    - wireguard_upgrade

