---

- name: Install linux headers (Ubuntu)
  apt:
    name:
      - linux-headers-generic
      - "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: yes
  tags:
    - wireguard_install

